[package]
name = "polly"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
once_cell = "1"
poise = "0.5"
rand = "0.8"
serde = "1"
serde_derive = "1"
serenity = { version = "0.11", default-features = false, features = [
    "cache",
    "client",
    "gateway",
    "rustls_backend",
    "model",
] }
tokio = { version = "1", features = ["full"] }
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
