[package]
name = "polly"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[[example]]
name = "polly"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
once_cell = "1"
poise = "0.5"
rand = "0.8"
serde = "1"
serde_derive = "1"
serenity = { version = "0.11", default-features = false, features = [
    "cache",
    "client",
    "gateway",
    "rustls_backend",
    "model",
] }
shuttle-secrets = "0.8"
shuttle-service = "0.8"
shuttle-static-folder = "0.8"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
tracing = "0.1"
tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[patch.crates-io]
# https://github.com/shuttle-hq/shuttle/issues/527
dashmap = { git = "https://github.com/snylonue/dashmap", branch = "no-toolchain" }
