[package]
name = "polly"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
once_cell = "1"
rand = "0.8"
serenity = { version = "0.11", default-features = false, features = [
    "cache",
    "client",
    "gateway",
    "rustls_backend",
    "model",
] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
