[package]
name = "polly"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[[example]]
name = "polly"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
once_cell = "1"
poise = "0.5"
rand = "0.8"
serde = "1"
serde_derive = "1"
serenity = { version = "0.11", default-features = false, features = [
    "cache",
    "client",
    "gateway",
    "rustls_backend",
    "model",
] }
shuttle-secrets = "*"
shuttle-service = { version = "0.11", features = ["bot-poise"] }
shuttle-static-folder = "*"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
tracing = "0.1"
tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
